create table member (
        deleted_date date,
        dept_cd varchar(2),
        login_fail_cnt integer default 0,
        marketing_app_date date,
        marketing_email_date date,
        marketing_kakao_date date,
        marketing_sms_date date,
        marketing_third_date date,
        otp_yn varchar(1) default 'N',
        use_yn char(1) default 'Y' check (use_yn in ('Y','N')),
        user_type varchar(3),
        gender varchar(6) check (gender in ('F','M')),
        jumin1 varchar(6),
        created_on timestamp(6) default CURRENT_TIMESTAMP,
        updated_on timestamp(6) default CURRENT_TIMESTAMP,
        zipcode varchar(20),
        member_register_type varchar(35) check (member_register_type in ('GENERAL','KAKAO','NAVER','APPLE','GOOGLE')),
        created_by varchar(50),
        updated_by varchar(50),
        tel_no varchar(100),
        user_nm varchar(100),
        user_nm_en varchar(100),
        email varchar(150),
        jumin2 varchar(150),
        otp_no varchar(150),
        user_id varchar(150),
        user_pw varchar(150),
        address1 varchar(200),
        address2 varchar(200),
        member_id varchar(255) not null,
        real_name_yn varchar(255) default 'N' check (real_name_yn in ('Y','N')),
        primary key (member_id),
        constraint uk01_member unique (user_id)
);