CREATE TABLE test
(
    test  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        constraint pk_question primary key,
    title VARCHAR(255) NOT NULL
);

create table member
(
    member_id            varchar(255) not null
        primary key,
    address1             varchar(200),
    address2             varchar(200),
    created_by           varchar(50),
    created_on           timestamp(6) default CURRENT_TIMESTAMP,
    updated_by           varchar(50),
    updated_on           timestamp(6) default CURRENT_TIMESTAMP,
    deleted_date         date,
    dept_cd              varchar(2),
    email                varchar(150),
    login_fail_cnt       integer      default 0,
    marketing_email_date date,
    marketing_kakao_date date,
    marketing_sms_date   date,
    member_register_type varchar(35)
        constraint member_member_register_type_check
            check ((member_register_type)::text = ANY
        ((ARRAY ['GENERAL'::character varying, 'KAKAO'::character varying, 'NAVER'::character varying, 'APPLE'::character varying, 'GOOGLE'::character varying])::text[])),
    otp_no               varchar(150),
    otp_yn               varchar(1)   default 'N'::character varying,
    tel_no               varchar(100),
    use_yn               char         default 'Y'::bpchar
        constraint member_use_yn_check
            check (use_yn = ANY (ARRAY ['Y'::bpchar, 'N'::bpchar])),
    user_id              varchar(150)
        constraint uk01_member
            unique,
    user_nm              varchar(100),
    user_nm_en           varchar(100),
    user_pw              varchar(150),
    user_type            varchar(3),
    zipcode              varchar(20)
);